Test suite: Use the new Python-based test client

diff --git a/test/runtests b/test/runtests
--- a/test/runtests
+++ b/test/runtests
@@ -47,26 +47,6 @@ function stop_msva()
     unset msva_pidfile
 }
 
-# Compare expected/actual outputs, filtering out headers from actual
-# output that are expected to change between runs or builds (currently
-# "Date", "Server" and "Content-Length"). The headers must be excluded
-# in the expected output.
-#
-# Parameters:
-# $1: path to expected output
-# $2: path to actual output
-# $3: additional options for diff (optional)
-function diff_output_filter_headers()
-{
-    local expected="$1"
-    local actual="$2"
-    diff $3 -u "${expected}" <( cat "${actual}" | \
-	grep -v -P '^Date:\s.*GMT\s?$' | \
-	grep -v -P '^Server:\sApache'  | \
-	grep -v -P '^Content-Length:\s\d+\s?$' | \
-	tail -n "$(wc -l < ${expected})" )
-}
-
 # Run a command, storing its PID in the given file
 # Usage: run_with_pidfile PIDFILE COMMAND [ARGS]
 function run_with_pidfile()
@@ -103,10 +83,6 @@ function kill_by_pidfile()
 function apache_down_err() {
     printf "FAILURE: %s\n" "$TEST_NAME"
     ${APACHE2} -f "${testdir}/apache.conf" -k stop || true
-    if [ -e output ]; then
-	printf "\ngnutls-cli outputs:\n"
-	diff_output_filter_headers "output" "$output" || true
-    fi
 
     if [ -r "${testdir}/backend.conf" ]; then
 	apache_service "${testdir}" "backend.conf" stop || true
@@ -114,10 +90,6 @@ function apache_down_err() {
 
     if [ -r "${testdir}/ocsp.conf" ]; then
 	apache_service "${testdir}" "ocsp.conf" stop || true
-    fi
-
-    if [ -n "${sleep_pidfile}" ]; then
-	kill_by_pidfile "${sleep_pidfile}"
     fi
 
     local errlog="logs/${TEST_NAME}.error.log"
@@ -223,41 +195,14 @@ else
     TARGET="${TEST_HOST}"
 fi
 
-# PID file for sleep command (explanation below)
-sleep_pidfile="$(mktemp mod_gnutls_test-XXXXXX.pid)"
-
-# The sleep call keeps the pipe from the subshell to gnutls-cli
-# open. Without it gnutls-cli would terminate as soon as sed is
-# done, and not wait for a response from the server, leading to
-# failing tests. Sending sleep to the background allows the test
-# case to proceed instead of waiting for it to return. The sleep
-# process is stopped after gnutls-cli terminates.
-#
-# The line end manipulation in sed guarantees that all header lines
-# end with CRLF as required by RFC 7230, Section 3.1.1 regardless of
-# the line ends in the input file.
-if (sed -r "s/__HOSTNAME__/${TEST_HOST}/;s/\r?$/\r/" <${testdir}/input && \
-	   run_with_pidfile "${sleep_pidfile}" sleep "${TEST_QUERY_TIMEOUT}" &) | \
-       gnutls-cli -p "${TEST_PORT}" $(cat ${testdir}/gnutls-cli.args) "${TARGET}" \
-       | tee "$output" && test "${PIPESTATUS[1]}" -eq 0;
-then
-    if [ -e ${testdir}/fail* ]; then
-        printf "%s should have failed but succeeded\n" "$(basename "$testdir")" >&2
-        exit 1
-    fi
-else
-    if [ ! -e ${testdir}/fail* ]; then
-        printf "%s should have succeeded but failed\n" "$(basename "$testdir")" >&2
-        exit 1
-    fi
+${PYTHON} ${srcdir}/https-test-client.py -p "${TEST_PORT}" "${TARGET}" \
+	  --test-config "${testdir}/test.yml"\
+    |& tee "$output"
+# We care about the exit status of the Python script, not tee
+if [ ${PIPESTATUS[0]} -ne 0 ]; then
+    exit 1
 fi
 
-kill_by_pidfile "${sleep_pidfile}"
-unset sleep_pidfile
-
-if [ -e ${testdir}/output ] ; then
-    diff_output_filter_headers "${testdir}/output" "$output" >&2
-fi
 if [ -n "${USE_MSVA}" ]; then
     trap stop_msva EXIT
 else
